kernel.randomize_va_space = 0
#vm.nr_hugepages=512
kernel.split_lock_mitigate=0
fs.protected_hardlinks = 0
fs.protected_symlinks = 0
fs.file-max = 2097152
vm.swappiness = 1
vm.overcommit_memory = 1
kernel.nmi_watchdog = 0
vm.stat_interval = 1000
kernel.sched_latency_ns = 6000000
kernel.sched_min_granularity_ns = 1500000
kernel.sched_wakeup_granularity_ns = 500000
kernel.sched_rt_runtime_us = -1
kernel.sched_autogroup_enabled = 0
kernel.softlockup_panic = 0
kernel.softlockup_all_cpu_backtrace = 0
vm.page_lock_unfairness = 1
vm.compaction_proactiveness=0
vm.dirty_expire_centisecs    = 600
vm.dirty_writeback_centisecs = 100
