#vm.nr_hugepages=512
vm.hugetlb_shm_group = 1000
vm.compaction_proactiveness = 0
vm.watermark_boost_factor = 1
vm.min_free_kbytes = 1048576
vm.watermark_scale_factor = 500
vm.swappiness = 1
vm.zone_reclaim_mode = 0
vm.page_lock_unfairness = 1
vm.overcommit_memory = 1
vm.max_map_count = 2147483642
vm.stat_interval = 1000
vm.dirty_expire_centisecs = 600
vm.dirty_writeback_centisecs = 100
vm.transparent_hugepage = madvise                
vm.transparent_hugepage.defrag = madvise
vm.transparent_hugepage.khugepaged.defrag = 0

kernel.numa_balancing=0
kernel.sched_child_runs_first = 0
kernel.sched_autogroup_enabled = 0
kernel.sched_cfs_bandwidth_slice_us = 3000
kernel.sched_latency_ns = 6000000
kernel.sched_min_granularity_ns = 1500000
kernel.sched_wakeup_granularity_ns = 500000
kernel.sched_rt_runtime_us = -1
kernel.randomize_va_space = 0
kernel.split_lock_mitigate = 0
kernel.kptr_restrict = 0
kernel.yama.ptrace_scope = 0 
kernel.nmi_watchdog = 0
kernel.softlockup_panic = 0
kernel.softlockup_all_cpu_backtrace = 0
kernel.hardlockup_panic = 0

net.core.netdev_max_backlog = 16384
net.core.rmem_default = 262144
net.core.rmem_max = 134217728
net.core.wmem_default = 262144
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 134217728
net.ipv4.tcp_wmem = 4096 65536 134217728
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_sack = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_congestion_control = bbr
net.core.default_qdisc = fq_codel

fs.file-max = 2097152                            
fs.inotify.max_user_watches = 524288             
fs.aio-max-nr = 1048576                         
fs.protected_hardlinks = 0                 
fs.protected_symlinks = 0                        


