# --- Système global ---
* soft nofile 524288
* hard nofile 1048576
* soft nproc 32768
* hard nproc 65536

# --- Gaming max performance (votre utilisateur) ---
linux soft rtprio 10
linux hard rtprio 20
linux - nice -10
linux soft memlock unlimited
linux hard memlock unlimited
linux soft stack 8192
linux hard stack 16384

# --- Root (au cas où) ---
root soft rtprio 99
root hard rtprio 99
root - nice -20
root soft memlock unlimited
root hard memlock unlimited
